#!/bin/bash -e
COMPSs_VERSION="3.3.rc2503"
SANDBOX="/tmp/agent_container"
rm -rf ${SANDBOX}
mkdir -p ${SANDBOX}

INIT_DIR=$(pwd)
RUNTIME_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../.. && pwd )"

echo "Copying framework to ${SANDBOX}"
cp -r -L "${RUNTIME_DIR}" ${SANDBOX}

echo "Removing Tests from maven"
sed -i -e 's#<module>tests/sources</module># #g'  ${SANDBOX}/compss/pom.xml
sed -i -e 's#<module>performance_analysis/auto-cbm</module># #g'  ${SANDBOX}/compss/pom.xml

# CLEANING MAVEN PROJECT
cd "${SANDBOX}"/compss
echo "Building image"
mvn clean

# BUILDING IMAGE
echo "Building image"
cd "${SANDBOX}"
docker build -t compss/agent:${COMPSs_VERSION} ./compss -f ./compss/utils/docker/agent/Dockerfile

rm -rf "${SANDBOX}"
cd "${INIT_DIR}"
